import os, sys
# coding=utf-8
fname = input('file name please:')
with open(fname, 'r') as myfile:
    jomle=myfile.read().replace('\n', '')
print ("number of ا:",jomle.count("ا"))
print ("number of ب:",jomle.count("ب"))
print ("number of پ:",jomle.count("پ"))
print ("number of ت:",jomle.count("ت"))
print ("number of ث:",jomle.count("ث"))
print ("number of ج:",jomle.count("ج"))
print ("number of چ:",jomle.count("چ"))
print ("number of ح:",jomle.count("ح"))
print ("number of خ:",jomle.count("خ"))
print ("number of د:",jomle.count("د"))
print ("number of ذ:",jomle.count("ذ"))
print ("number of ر:",jomle.count("ر"))
print ("number of ز:",jomle.count("ز"))
print ("number of ژ:",jomle.count("ٓٓژ"))
print ("number of س:",jomle.count("س"))
print ("number of ش:",jomle.count("ش"))
print ("number of ص:",jomle.count("ص"))
print ("number of ض:",jomle.count("ض"))
print ("number of ط:",jomle.count("ط"))
print ("number of ظ:",jomle.count("ظ"))
print ("number of ع:",jomle.count("ع"))
print ("number of غ:",jomle.count("غ"))
print ("number of ف:",jomle.count("ف"))
print ("number of ق:",jomle.count("ق"))
print ("number of ک:",jomle.count("ک"))
print ("number of گ:",jomle.count("گ"))
print ("number of ل:",jomle.count("ل"))
print ("number of م:",jomle.count("م"))
print ("number of ن:",jomle.count("ن"))
print ("number of و:",jomle.count("و"))
print ("number of ه:",jomle.count("ه"))
print ("number of ی:",jomle.count("ی"))